### ISSUE TITLE
No module named 'numpy.random.common'

### ISSUE THREAD

**Issue by Raazzta** [Matix-Media/PickleViewer#3]
**Describe the bug**

**To Reproduce**
1. Go to 'run app'
2. Click on 'choose menu File - Open Pickle File'
3. Scroll down to '-'

**Expected behavior**
After open pickle file, I want to see the content of file.

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/52389138/69230800-4610e380-0bcb-11ea-954e-d494a35475a0.png)
.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Matix-Media** [comment]
you can send the file you wanted to open?

**Comment by Raazzta** [comment]
https://github.com/noureldien/videograph/blob/master/data/epic_kitchens/annotation/video_names_splits.pkl

**Comment by Matix-Media** [comment]
So you used a not default object in the file?

**Comment by Raazzta** [comment]
That's not my work actually

**Comment by Matix-Media** [comment]
okay, I take a look when I'm back at home

**Comment by alfredlu1986** [comment]
I also encounter this issue, but may error log is No module named 'Pandas'

**Comment by Matix-Media** [comment]
I know whats the error. I gonna patch this in the next update. The error is that the pickle files contain data from external packages that PickleViwer did not import. I'll see if I can fix the file reading.
