### ISSUE TITLE
Linux version / Available source

### ISSUE THREAD

**Issue by pavolgaj** [Matix-Media/PickleViewer#4]
Your software is great but, unfortunately, it works only on Windows. Don't you plan to make also a version for Linux? Could you publish the source code? It'll be great - it would be used on any OS (just installing python and necessary packages would be needed).

**Comment by Matix-Media** [comment]
Yes, I am also planning to publish the source code because I no longer have time to take care of the project. The code is not particularly nice, but maybe you can do something with it.
