### ISSUE TITLE
Series of pickles in file

### ISSUE THREAD

**Issue by rapzak** [Matix-Media/PickleViewer#5]
Hi,

I have made a system where i append several pickles to one file - then the viewer only shows the first pickles.
I like it to continue scan the file for more pickles in the same file and show them all.
I can supply sample file
Thanks

**Comment by Matix-Media** [comment]
Hi, I am sorry to tell you that I stopped working on this project. If you want to implement this feature, go ahead. The source-code is deployed in the repository.
